export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE'
}

export const userConstants = {
    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE'
}

export const categoryConstants = {
    GET_ALL_CATEGORIES_REQUEST: 'GET_ALL_CATEGORIES_REQUEST',
    GET_ALL_CATEGORIES_SUCCESS: 'GET_ALL_CATEGORIES_SUCCESS',
    GET_ALL_CATEGORIES_FAILURE: 'GET_ALL_CATEGORIES_FAILURE',

    ADD_NEW_CATEGORY_REQUEST: 'ADD_NEW_CATEGORY_REQUEST',
    ADD_NEW_CATEGORY_SUCCESS: 'ADD_NEW_CATEGORY_SUCCESS',
    ADD_NEW_CATEGORY_FAILURE: 'ADD_NEW_CATEGORY_FAILURE',

    UPDATE_CATEGORIES_REQUEST: 'UPDATE_CATEGORIES_REQUEST',
    UPDATE_CATEGORIES_SUCCESS: 'UPDATE_CATEGORIES_SUCCESS',
    UPDATE_CATEGORIES_FAILURE: 'UPDATE_CATEGORIES_FAILURE',

    DELETE_CATEGORIES_REQUEST: 'DELETE_CATEGORIES_REQUEST',
    DELETE_CATEGORIES_SUCCESS: 'DELETE_CATEGORIES_SUCCESS',
    DELETE_CATEGORIES_FAILURE: 'DELETE_CATEGORIES_FAILURE'
}

export const productConstants = {
    GET_ALL_PRODUCTS_REQUEST: 'GET_ALL_PRODUCTS_REQUEST',
    GET_ALL_PRODUCTS_SUCCESS: 'GET_ALL_PRODUCTS_SUCCESS',
    GET_ALL_PRODUCTS_FAILURE: 'GET_ALL_PRODUCTS_FAILURE',

    ADD_NEW_PRODUCT_REQUEST: 'ADD_NEW_PRODUCT_REQUEST',
    ADD_NEW_PRODUCT_SUCCESS: 'ADD_NEW_PRODUCT_SUCCESS',
    ADD_NEW_PRODUCT_FAILURE: 'ADD_NEW_PRODUCT_FAILURE',

    DELETE_PRODUCT_BY_ID_REQUEST: 'DELETE_PRODUCT_BY_ID_REQUEST',
    DELETE_PRODUCT_BY_ID_SUCCESS: 'DELETE_PRODUCT_BY_ID_SUCCESS',
    DELETE_PRODUCT_BY_ID_FAILURE: 'DELETE_PRODUCT_BY_ID_FAILURE',
}

export const initialDataConatants = {
    GET_ALL_INITIAL_DATA_REQUEST: 'GET_ALL_INITIAL_DATA_REQUEST',
    GET_ALL_INITIAL_DATA_SUCCESS: 'GET_ALL_INITIAL_DATA_SUCCESS',
    GET_ALL_INITIAL_DATA_FAILURE: 'GET_ALL_INITIAL_DATA_FAILURE',
}

export const pageConstants = {
    CREATE_PAGE_REQUEST: 'CREATE_PAGE_REQUEST',
    CREATE_PAGE_SUCCESS: 'CREATE_PAGE_SUCCESS',
    CREATE_PAGE_FAILURE: 'CREATE_PAGE_FAILURE',
}

export const orderConstants = {
    GET_CUSTOMER_ORDER_REQUEST: "GET_CUSTOMER_ORDER_REQUEST",
    GET_CUSTOMER_ORDER_SUCCESS: "GET_CUSTOMER_ORDER_SUCCESS",
    GET_CUSTOMER_ORDER_FAILURE: "GET_CUSTOMER_ORDER_FAILURE",
  
    UPDATE_CUSTOMER_ORDER_REQUEST: "UPDATE_CUSTOMER_ORDER_REQUEST",
    UPDATE_CUSTOMER_ORDER_SUCCESS: "UPDATE_CUSTOMER_ORDER_SUCCESS",
    UPDATE_CUSTOMER_ORDER_FAILURE: "UPDATE_CUSTOMER_ORDER_FAILURE",
};

export const brandConstants = {
    GET_ALL_BRAND_REQUEST: 'GET_ALL_BRAND_REQUEST',
    GET_ALL_BRAND_SUCCESS: 'GET_ALL_BRAND_SUCCESS',
    GET_ALL_BRAND_FAILURE: 'GET_ALL_BRAND_FAILURE',

    ADD_NEW_BRAND_REQUEST: 'ADD_NEW_BRAND_REQUEST',
    ADD_NEW_BRAND_SUCCESS: 'ADD_NEW_BRAND_SUCCESS',
    ADD_NEW_BRAND_FAILURE: 'ADD_NEW_BRAND_FAILURE',

    UPDATE_BRAND_REQUEST: 'UPDATE_BRAND_REQUEST',
    UPDATE_BRAND_SUCCESS: 'UPDATE_BRAND_SUCCESS',
    UPDATE_BRAND_FAILURE: 'UPDATE_BRAND_FAILURE',
    
    DELETE_BRAND_REQUEST: 'DELETE_BRAND_REQUEST',
    DELETE_BRAND_SUCCESS: 'DELETE_BRAND_SUCCESS',
    DELETE_BRAND_FAILURE: 'DELETE_BRAND_FAILURE'
};

export const tagConstants = {
    GET_ALL_TAGS_REQUEST: 'GET_ALL_TAGS_REQUEST',
    GET_ALL_TAGS_SUCCESS: 'GET_ALL_TAGS_SUCCESS',
    GET_ALL_TAGS_FAILURE: 'GET_ALL_TAGS_FAILURE',

    ADD_NEW_TAG_REQUEST: 'ADD_NEW_TAG_REQUEST',
    ADD_NEW_TAG_SUCCESS: 'ADD_NEW_TAG_SUCCESS',
    ADD_NEW_TAG_FAILURE: 'ADD_NEW_TAG_FAILURE',
}